# Pls keep it in alphabetical order. Thx!
# info @ https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

# Check out the js-hook part!
# https://github.com/airbnb/css/blob/master/.scss-lint.yml

linters:
  ColorVariable:
    enabled: false
  # Disable declaration order so we can put design rules in the end via @include to separate structure & design layers
  DeclarationOrder:
    enabled: false
  FinalNewline:
    enabled: false
  HexLength:
    style: short
  # Internal snippets like mixins and design layer files start with an underscore
  ImportPath:
    leading_underscore: true
  Indentation:
    character: tab
    width: 1
  LeadingZero:
    style: include_zero
  NestingDepth:
    max_depth: 4
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    max_depth: 4
  # For some reason this does not work with "scss-lint:disable"
  SingleLinePerSelector:
    enabled: false
  SpaceAfterPropertyColon:
    style: at_least_one_space
  SpaceBeforeBrace:
    allow_single_line_padding: true
  # Please use all design related properties according to the existing palette mixins
  VariableForProperty:
    enabled: true,
    properties:
      # TODO: enable these when everything is ready
      #- background-color
      #- color
      - font
  # Remove this when dropping some of the browser support
  VendorPrefix:
    enabled: false